name: "CI"

on:
  pull_request:

jobs:
  test:
    uses: ./.github/workflows/test.yml

  automerge:
    uses: ./.github/workflows/automerge.yml
    needs:
      - test
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

# vim:ft=yaml:et:ts=2:sw=2
